name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET 9.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0'  # .NET 9.0 version setup

    - name: Install OpenSSL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev  # Install OpenSSL dependencies for .NET

    - name: Restore dependencies
      run: dotnet restore  # This should now work with OpenSSL installed

    - name: Publish the application
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Render
      run: |
        curl -fsSL https://render.com/deploy/github-action | bash
